project:
  type: website

website:
  title: "Course Materials Handbook"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      
  margin-header: | 
    ![](assets/aulogo_uk_var2_blue.png)
  favicon: assets/aulogo_uk_var2_blue.png

format:
  html:
    theme:
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
    css: styles.css
    toc: true
    mainfont: "inter, sans-serif"
    monofont: "JetBrains Mono, monospace"




